name: flutter_module
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^2.0.7
  dio: 1.0.1  #latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - images/img_load_fail.png

  module:
    androidPackage: com.example.fluttermodule
